### ISSUE TITLE
Playground grid overdraws page

### ISSUE THREAD

**Issue by siaarzh** [vadirn/starter-pack#2]
Can't use any features once toggling grid in playground options.

Steps to replicate:
0. start server
1. goto /playground and toggle grid

System:
- Windows 10 Pro v1803 (build 17134.648)
- Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by vadirn** [comment]
That's intended. Grid is there to check how things align, so it has to overlay everything.
